
import type { Metadata } from "next";
import "./globals.css";
import { Anton } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footers from "@/components/Footers";
import FramerProvider from "@/components/FramerProvider";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Kalolwala & Associates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> <Navbar/>
      <body className={`${anton.variable} antialiased`}>
       
        <FramerProvider>
          {children}
        </FramerProvider>
        
      </body><Footers/>
    </html>
  );
}
